name = "EnergyModelsRenewableProducers"
uuid = "b007c34f-ba52-4995-ba37-fffe79fbde35"
authors = ["Sigmund Eggen Holm <Sigmund.Holm@sintef.no>, Julian Straus <Julian.Straus@sintef.no>"]
version = "0.2.0"

[deps]
EnergyModelsBase = "5d7e687e-f956-46f3-9045-6f5a5fd49f50"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
TimeStructures = "260f4295-b40d-47c0-843b-64f3de373d90"

[compat]
EnergyModelsBase = "0.3.0"
JuMP = "1.5"
TimeStructures = "0.1.10"
julia = "^1.6"
